worker_num: 4
TrainReader_u:
  sample_transforms:
  - Decode: {}
  - RGBReverse_unidet: {}
  - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}
  - RandomFlip: {prob: 0.5}
  - NormalizeImage: {is_scale: false, mean: [103.5300,116.2800,123.6750], std: [1, 1,1]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 4
  shuffle: false
  drop_last: false
  collate_batch: false
  sample_epoch_size: 1600
  dataset_ratio: [1,1,1]
  muti_dataset_use_cas: [False,True,True]


EvalReader:
  sample_transforms:
  - Decode: {}
  - RGBReverse_unidet: {}
  - RandomShortSideResize: { short_side_sizes: [800], max_size: 1333 }
  - NormalizeImage: {is_scale: false, mean: [103.5300,116.2800,123.6750], std: [1, 1,1]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
  drop_last: false


TestReader:
  sample_transforms:
  - Decode: {}
  - RGBReverse: {}
  - Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: false, mean: [103.5300,116.2800,123.6750], std: [1, 1,1]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
  drop_last: false
